#!/bin/zsh

# This script creates a sample blog post and copies it to the content/blog directory
# In a real setup, you would push this to your GitHub repository

# Get today's date
TODAY=$(date +%Y-%m-%d)
FILENAME=sample-post-$(date +%Y%m%d)

# Make sure the content/blog directory exists
mkdir -p content/blog

# Create a new sample blog post
cat > content/blog/${FILENAME}.md << EOF
---
title: "Sample Blog Post ${TODAY}"
date: "${TODAY}"
excerpt: "This is a sample blog post generated by the create-sample-post.sh script."
category: "Sample"
tags: ["sample", "test", "markdown"]
coverImage: "/images/blog/default-cover.jpg"
author: "Chanthawat"
authorImage: "/profile.jpeg"
authorBio: "Software Engineering student at UTCC passionate about modern web technologies. Specializing in React, Next.js, and TypeScript development. Always exploring new tools and frameworks to build better user experiences."
---

# Sample Blog Post

This is a sample blog post generated by the create-sample-post.sh script.

## Markdown Features

Here are some Markdown features you can use in your blog posts:

### Lists

- Item 1
- Item 2
- Item 3

### Code Blocks

\`\`\`javascript
function helloWorld() {
  console.log("Hello, world!");
}
\`\`\`

### Blockquotes

> This is a blockquote. It can be used to highlight important information.

## Conclusion

Now you have a new blog post in your content/blog directory!
EOF

echo "Created a new sample blog post in content/blog directory: ${FILENAME}.md"
echo "You can now run your Next.js application to see it on your blog"
