# This workflow will do a clean installation of dependencies, cache/restore them, build the source code using Bun
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bun CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Check for broken links
        run: bun run check-links

      - name: Validate affiliate images
        run: bun run check-images
